export const URINE_COLORS = [
  {
    id: 'pale_yellow',
    label: 'Pale Yellow',
    hex: '#F5F0A0',
    meaning: 'Well hydrated — normal',
    action: 'normal' as const,
  },
  {
    id: 'yellow',
    label: 'Yellow',
    hex: '#F5D800',
    meaning: 'Normal hydration — normal',
    action: 'normal' as const,
  },
  {
    id: 'dark_yellow',
    label: 'Dark Yellow',
    hex: '#C8A800',
    meaning: 'Concentrated — drink more water',
    action: 'monitor' as const,
  },
  {
    id: 'amber',
    label: 'Amber',
    hex: '#C87800',
    meaning: 'Very concentrated or mild dehydration',
    action: 'monitor' as const,
  },
  {
    id: 'orange',
    label: 'Orange',
    hex: '#C85A00',
    meaning: 'Dehydration or medication effect',
    action: 'contact_doctor' as const,
  },
  {
    id: 'brown',
    label: 'Brown',
    hex: '#7B3A10',
    meaning: 'Possible liver or muscle issue, or medication effect',
    action: 'contact_doctor' as const,
  },
  {
    id: 'pink_red',
    label: 'Pink / Red',
    hex: '#E05A5A',
    meaning: 'Blood in urine (hematuria)',
    action: 'urgent' as const,
  },
  {
    id: 'cloudy_white',
    label: 'Cloudy / White',
    hex: '#E8E8D0',
    meaning: 'Possible UTI or kidney issue',
    action: 'contact_doctor' as const,
  },
  {
    id: 'dark_brown_cola',
    label: 'Dark Brown / Cola',
    hex: '#3D1A00',
    meaning: 'Severe muscle breakdown or liver issue',
    action: 'urgent' as const,
  },
  {
    id: 'green_blue',
    label: 'Green / Blue',
    hex: '#5A8A6A',
    meaning: 'Medication or food effect',
    action: 'monitor' as const,
  },
] as const
